### PR TITLE
Dyn-6750-new-open-update

### PR DESCRIPTION
**Pull request by dnenov**
## Purpose

This PR addresses a jira request for improvement of the HomePage: `As a Dynamo user, I would like to have New and Open buttons in app home to have default actions` https://jira.autodesk.com/browse/DYN-6750.

> By default, clicking on the button should perform the default action.
> New -> New workspace
> Open -> Open File
> 
> Only the dropdown should show other options
> New ...
>  - Workspace
> 
> Custom Node
> Open ...
> 
> Open File
> Open Template
> Backup Locations
> Also can shit New to the top top?

### UI Changes

DynamoSandbox_qkOXGy4Uo6

## Changes

- now separates the 'button' from the 'drop-down' functionality of the 'Open' and 'New' HomePage buttons.
- visual rehaul with @Jingyi-Wen 
- version bump

## Reviewer

@QilongTang
@Amoursol

### CODE REVIEW

**Comment by QilongTang** [comment]
This one becomes hard to review because it contains changes in the other preferences PR..

**Comment by dnenov** [comment]
> This one becomes hard to review because it contains changes in the other preferences PR..

Understood, Aaron - should I try to restructure it and remove the Preferences changes .. or wait to merge the Preferences PR and pull the latest main branch maybe?

**Comment by QilongTang** [comment]
> > This one becomes hard to review because it contains changes in the other preferences PR..
> 
> Understood, Aaron - should I try to restructure it and remove the Preferences changes .. or wait to merge the Preferences PR and pull the latest main branch maybe?

I would remove the preferences changes and keep it clean because this could land earlier than the other sets of PR

**Comment by dnenov** [comment]
> > > This one becomes hard to review because it contains changes in the other preferences PR..
> > 
> > 
> > Understood, Aaron - should I try to restructure it and remove the Preferences changes .. or wait to merge the Preferences PR and pull the latest main branch maybe?
> 
> I would remove the preferences changes and keep it clean because this could land earlier than the other sets of PR

Done, @QilongTang! Thanks for the pointers!!

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
